### ISSUE TITLE
TypeError: storage.initSync is not a function

### ISSUE THREAD

**Issue by niebomin** [giangvo/alfred-workflow-nodejs#22]
I have an exception.  Node version is `v14.17.5.`
```node
storage.initSync();
            ^

TypeError: storage.initSync is not a function
    at Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8F6BE96-BE8B-4524-8F7F-873C8C80E4EB/node_modules/alfred-workflow-nodejs/alfredNode.js:171:13
    at Object.<anonymous> (Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8F6BE96-BE8B-4524-8F7F-873C8C80E4EB/node_modules/alfred-workflow-nodejs/alfredNode.js:214:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8F6BE96-BE8B-4524-8F7F-873C8C80E4EB/main.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

**Comment by alexander9306** [comment]
I have the same issue on node js v16

**Comment by giangvo** [comment]
Hi, the issue was because the example workflow (`AlfredNodejsWorkflow.alfredworkflow`) had an old version of this library. I have updated the example workflow with the latest version. You should be able to redownload and import in to Alfred.
